"""Render completed local Codex stage; no model or grader calls."""
import csv,json,re
from pathlib import Path
OUT=Path(__file__).resolve().parent
records=json.loads((OUT/'codex-results.json').read_text());assert len(records)==4 and all('grade_exit_code' in r for r in records)
labels={'none':'No skill','karpathy':'Karpathy','candidate':'Locate-first candidate','both':'Candidate + Karpathy (Both)'}
byarm={r['arm']:r for r in records}; candidate=byarm['candidate']['reported_total_tokens'];ratios={a:100*(candidate/byarm[a]['reported_total_tokens']-1) for a in ('none','karpathy','both')}
counts={a:int(re.search(r'Executed accepted tests:\s*(\d+)',(OUT/'codex'/a/'grade.txt').read_text()).group(1)) if r['solved'] else None for a,r in byarm.items()}
with (OUT/'summary-codex.csv').open('w') as f:
 writer=csv.DictWriter(f,fieldnames=['harness','arm','solved','reported_total_tokens','elapsed_seconds']);writer.writeheader();writer.writerows({k:r[k] for k in writer.fieldnames} for r in records)
metadata={'stage_status':'Codex complete; Pi unstarted and requires fresh human login/root authorization','benchmark':'Aider polyglot adapted native Go single-attempt','task':'go/exercises/practice/food-chain','public_task_previously_exposed':True,'actor_starts_codex':4,'actor_starts_pi':0,'verified_solves':sum(r['solved'] is True for r in records),'executed_accepted_tests_per_arm':counts,'timeouts':sum(r['timeout'] for r in records),'auth_errors':sum(r['execution_status']=='blocked_auth_or_quota' for r in records),'actor_seconds':sum(r['elapsed_seconds'] for r in records),'configured_backend':'ChatGPT OAuth gpt-6.1-sol, native default effort','independently_observed_actual_backend':'TBD','billing_usd':'TBD','candidate_vs_comparison_token_change_percent':ratios,'order_seed':107,'model_sampling_seed':'TBD','canonical_promoted':False,'sealed_confirmation_used':False,'global_budget_binding_timing':'Supplemental matching global budget hash recorded after two starts; local8-start plan/authorization existed beforecalls, retained immutable'}
(OUT/'stage-progress.json').write_text(json.dumps(metadata,indent=2)+'\n')
lines=['# Locate-first Go development — Codex results','','Four bounded Codex attempts on previously exposed public Aider polyglot task `go/exercises/practice/food-chain`. Pi has zero starts and awaits fresh human login plus root authorization. One round; no promotion and no clean held-out claim.','','| Skill | Solved | Reported tokens | Actor seconds |','|---|---:|---:|---:|']
for a,label in labels.items():
 r=byarm[a];lines.append(f'| {label} | {int(r["solved"]) if r["solved"] is not None else "TBD"}/1 | {r["reported_total_tokens"]:,} | {r["elapsed_seconds"]:.1f} |')
lines+=['',f'Locate-first uses **{ratios["none"]:+.1f}%** reported tokens versus no skill, **{ratios["karpathy"]:+.1f}%** versus Karpathy, and **{ratios["both"]:+.1f}%** versus Both. This does not prove stable efficiency or generalization. Actual dollars remain **TBD**.','','Configured backend: ChatGPT OAuth `gpt-6.1-sol`, native default effort; a separately observed actual backend label is **TBD**. Complete terminal counters are summed once, including reported cached usage. Order seed107 controls arm order, not model randomness.','','The immutable local `plan.json` and `budget.json` froze eight starts, four per harness,180-second caps, no retries, full skill/source/prompt/runtime/grader hashes, and image `sha256:be1506c27383f1294c827041f4705d45a7342ca01273e7fbb47ff69df875b118` before calls. Codex alone was explicitly launched. The root broad-stage budget instruction arrived after first start; its matching allocation/hash was supplementally recorded after two starts in `global-budget-binding.json`. This limitation is disclosed; the local frozen plan was not rewritten.','','Actors received the original public prompt, solution template and Go module, uniform inline instructions, and complete readonly skill resource bundles. Original test files were absent from actors. After actors stopped, the pinned trusted grader restored original official exercise tests into a scratch copy, ignored actor test/build configuration, and ran Go JSON tests in network-disabled Docker with no credentials. Baseline template grading rejected before inference. Each grade preserves raw Go events and executed-test counts; `audit.py` verifies hashes and counts. This is an adapted native single-attempt evaluation, not the original Aider multi-turn harness.','','`external-fetch-audit.json` examines saved command/native-web traces for network and official-test access candidates. A lack of markers does not prove isolation: task history includes prior development exposure and external fetches in earlier agents. Never describe this as clean held-out confirmation. All failures, timeouts and missing usage remain visible; auth failures would be availability records, not free quality zeros.','','Private credential caches live outside Git and preserve refresh updates. The same per-harness `cache/codex.lock` serializes model attempts with the concurrent terminal stage. Host credential seeds are never written. Original and refreshed exact credential values are checked locally without logging them. Pi remains gated.','','Artifacts: [Codex results](codex-results.json), [summary](summary-codex.csv), [external-fetch audit](external-fetch-audit.json), [security/grader audit](audit.json), [stage progress](stage-progress.json). Raw transcripts, patches, final source workspaces and grader outputs remain under `codex/`. Canonical skill and sealed confirmation tasks are unchanged.']
text='\n'.join(lines)+'\n'
for a,b in [('seed107','seed 107'),('harness,180','harness, 180')]:text=text.replace(a,b)
(OUT/'README.md').write_text(text);print(json.dumps(metadata))
