"""Render only complete official reports. No model calls."""
import csv,hashlib,json
from pathlib import Path
OUT=Path(__file__).resolve().parent
records=json.loads((OUT/'results.json').read_text())
assert len(records)==12 and all(r['solved'] is not None for r in records)
traces=json.loads((OUT/'trace-audit.json').read_text())['records']
for r in records:
 t=next(t for t in traces if t['path']==r['harness']+'/'+r['arm']);r['tool_calls']=t['tool_calls'];r['observed_models']=t['observed_models'];r['model_observation']=t['actual_model_observation']
 dest=OUT/r['harness']/r['arm']; assert hashlib.sha256((dest/'stdout.jsonl').read_bytes()).hexdigest()==r['transcript_sha256'];assert hashlib.sha256((dest/'model.patch').read_bytes()).hexdigest()==r['patch_sha256']
 assert hashlib.sha256((OUT/r['official_report']).read_bytes()).hexdigest()==r['official_report_sha256']
 (dest/'result.json').write_text(json.dumps(r,indent=2)+'\n')
(OUT/'results.json').write_text(json.dumps(records,indent=2)+'\n')
with (OUT/'summary.csv').open('w') as f:
 writer=csv.DictWriter(f,fieldnames=['harness','arm','solved','reported_total_tokens','elapsed_seconds','tool_calls']); writer.writeheader();writer.writerows({k:r[k] for k in writer.fieldnames} for r in records)
lines=['# SWE-bench native development screen','','Twelve bounded Docker actors on one public SWE-bench Verified development issue, `pallets__flask-5014`. One round; order seed 105 controls order, not model randomness. No held-out confirmation and no skill promotion.','','| Harness | Skill | Solved | Reported tokens | Actor seconds |','|---|---|---:|---:|---:|']
labels={'none':'No skill','karpathy':'Karpathy','shipped':'Shipped ours','leanparent':'Lean parent','candidate':'No-reread candidate','both':'Candidate + Karpathy (Both)'}
for h in ('pi','codex'):
 for a in labels:
  r=next(r for r in records if r['harness']==h and r['arm']==a); lines.append(f'| {h} | {labels[a]} | {int(r["solved"])}/1 | {r["reported_total_tokens"]:,} | {r["elapsed_seconds"]:.1f} |')
lines+=['','The no-reread candidate uses **78.3% more** reported tokens than no skill in Pi and **7.1% more** in Codex. Shipped ours uses **23.9%** more in Pi and **19.5%** fewer in Codex. These are single-task descriptive observations, not stability or statistical evidence. The candidate is not promoted.','','Pi uses OpenAI `gpt-6.1-sol`, thinking low; its completed message events confirm that model label. Codex explicitly selects `gpt-6.1-sol` with native default effort and ChatGPT OAuth; a separately observed actual backend label is **TBD**. Complete terminal counters are summed once; they include reported cached usage and are not verified invoice amounts. Actual dollars: **TBD**. Cross-harness efforts and tools differ.','','All actors received the original public issue and fresh single-commit source snapshot, uniform inline skill text, and readonly resources. Gold patches, private dataset and official tests were never mounted into actors. Actor cap 180 seconds, maximum 12 attempts, no retries; all 12 exited 0 without timeouts. `plan.json` froze the model matrix, skill/prompt hashes and image ID before inference. Runner/source hashes were omitted from that plan and recorded during execution; this limitation is explicit in `runtime-provenance.json`.','','After actors stopped, `bridge-executed.py` rebuilt patches against trusted original snapshots while ignoring actor Git indexes/history. Each saved `model.patch` was independently graded with official `swebench 5.0.2` `run_evaluation` against the pinned private dataset, revision `78f471bf655a3137b2e8a75af1501690ec009ec3`. Official reports and test outputs are under `official/`; hashes appear in every result. An empty-patch sanity was initially skipped by the official harness, preserved as incomplete. Before any actor ran, a harmless marker no-op obtained a real official report with resolved=false and the expected target test failure; no model attempt was replayed. Prior gold sanity resolved=true is in `../../swe-native-sanity/` and `../../grader-sanity/`.','','Runtime and trace limitations: Pi Bash tool calls report `rg` unavailable while Codex command tools resolve it; all Pi arms attempted it and recovered with other tools. The PATH/tool-wrapper mechanism is **TBD**. No environment was changed within this screen. Three unrelated `test_basic.py` cookie-domain failures persist with original official image dependencies even after gold. Codex Lean parent ran the full suite and encountered those failures; Karpathy ran broader basic tests. These failures are disclosed rather than interpreted as regressions in the official task result. Saved traces show no redundant SKILL.md reads in this fixture, so the no-reread sentence does not explain a measured causal benefit.','','Full-suite cleanliness, generalization across tasks/harnesses, repeated-round stability, and real billing superiority remain **TBD**.']
(OUT/'README.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({'attempts':len(records),'solved':sum(r['solved'] for r in records)}))
