"""Read-onlysyntheticgateaudit;FAKEusageisNOTproviderbilling/qualityproof."""
import json,pathlib,hashlib
from audit_16k_tex import native_events,events
from prospective_output_budget import module
R=pathlib.Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
if __name__=='__main__':
 p=json.loads((R/'admission-native-probe-plan.json').read_text());v=json.loads((R/'admission-native-probe.json').read_text());assert v['plan_sha256']==sha(R/'admission-native-probe-plan.json') and sha(R/'run_admission_native_probe.py')==p['runner_sha256'] and sha(R/'prospective_broker_admission.py')==p['prospective_module_sha256'];root=pathlib.Path(v['private_root']);assert all(sha(root/n)==h for n,h in v['artifact_hashes'].items());D=R.parent/'development/pi-takeover-qwen-source-backed-16k/runtime';assert all(sha(D/n)==h for n,h in p['original_runtime_hashes'].items());assert v['passed'] and all(v[k] for k in ['cleanup_containers_absent','cleanup_network_absent','workers_exited','all_original_runtime_hashes_unchanged']);assert v['real_model_POST']==v['real_generated_tokens']==v['scored_actor_starts']==v['official_test_or_gold_runs']==0 and v['synthetic_native_starts']==1
 ledger=json.loads((root/'transport/ledger.json').read_text());views=json.loads((root/'transport/prospective-ledger.json').read_text())['records'];assert ledger['native_starts']==1 and ledger['provider_POST']==len(ledger['records'])==len(views)==v['fake_exchanges']==2
 strict=module('gate_strict',(D/'usage_normalization.py').read_text());costmodule=module('gate_cost',(D/'provider_cost.py').read_text().replace('from usage_normalization import normalize_request',''),{'normalize_request':strict.normalize_request});costs=[]
 for request,view in zip(ledger['records'],views):
  n=request['request'];raw=root/'transport'/f'response-{n}.sse';derived=root/'transport'/f'derived-response-{n}.sse';assert sha(raw)==view['raw_sha256'] and sha(derived)==view['derived_sha256'] and raw.read_bytes()==derived.read_bytes();cost=costmodule.normalize_cost(events(raw),request['stream_eof']);assert cost==view['accounting_view']['derived_cost'] and cost['provider_cost_complete'] and cost['generation_complete'] and cost['protocol_valid'];assert request['error'] is None and request['provider_status']==200 and request['payload_policy']['output_cap']==16384;assert json.loads((root/'transport'/f'forwarded-request-{n}.json').read_text())['max_output_tokens']==16384;costs.append(cost)
 native=native_events(root/'native.jsonl');turns=[e for e in native if e.get('type')=='turn.completed'];assert len(turns)==1 and not any(e.get('type')=='turn.failed' for e in native);assert any(e.get('type')=='item.completed' and e.get('item',{}).get('type')=='command_execution' and e['item']['exit_code']==0 for e in native);assert any(e.get('type')=='item.completed' and e.get('item',{}).get('text','').strip()=='ACK' for e in native)
 for nk,ck in [('input_tokens','input_tokens_inclusive'),('output_tokens','output_tokens_inclusive'),('reasoning_output_tokens','reasoning_tokens_reported')]:assert turns[0]['usage'][nk]==sum(c[ck] for c in costs)
 assert v['synthetic_gross_usage']==sum(c['gross_tokens'] for c in costs)==226 and v['deadline_not_extended'] and len(v['controlled_terminal_holds'])==1 and v['controlled_terminal_holds'][0]>=.35;assert json.loads((root/'admission.json').read_text())['records']==[];reject=json.loads((root/'broker-byte.json').read_text())['records'];assert reject==v['byte_rejections'] and len(reject)==1 and reject[0]['provider_forwarded'] is False and reject[0]['provider_POST']==0 and reject[0]['status']==v['overcap_status']==413
 audit={'plan_sha256':v['plan_sha256'],'gate_passed':True,'actual_native_tool_and_followup_confirmed':True,'fake_native_jobs':1,'fake_exchanges':2,'no429_or_failed_native_turn':True,'usage_rebuilt_and_fake_native_reconciled':True,'synthetic_gross_usage_NOT_billing':226,'real_model_POST':0,'original_frozen_runtime_unchanged':True,'cleanup_verified':True,'historical_native429_exact_cause_confirmed':False,'skill_or_quality_economy_proven':False,'goal_complete':False};(R/'admission-native-probe-audit.json').write_text(json.dumps(audit,indent=2)+'\n');print(json.dumps(audit,indent=2))
