"""Failure-inclusive audit ALLstartedactors; unknowncostnotzero/gradeunavailable."""
import pathlib,json,hashlib,subprocess
from audit_16k_tex import events,native_events
from audit_16k_regex import validate_response
from prospective_output_budget import module
R=pathlib.Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
if __name__=='__main__':
 plan=json.loads((R/'coalesced-fasttext-plan.json').read_text());digest=sha(R/'coalesced-fasttext-plan.json');result=json.loads((R/'coalesced-fasttext-result.json').read_text());graded=json.loads((R/'coalesced-fasttext-audit.json').read_text());assert result['plan_sha256']==graded['plan_sha256']==digest and not graded['stage_complete'];root=pathlib.Path('/tmp/solpi-cf16-'+digest[:18]);D=R.parent/'development/pi-takeover-qwen-coalesced-verification-admission-16k/runtime';strict=module('failure_strict',(D/'usage_normalization.py').read_text());costs=module('failure_cost',(D/'provider_cost.py').read_text().replace('from usage_normalization import normalize_request',''),{'normalize_request':strict.normalize_request});adapter=module('failure_adapter',(D/'reasoning_adapter.py').read_text().replace('from provider_cost import normalize_cost',''),{'normalize_cost':costs.normalize_cost,'__file__':str(D/'reasoning_adapter.py')});ledger=json.loads((root/'transport/ledger.json').read_text());views={x['request']:x for x in json.loads((root/'transport/prospective-ledger.json').read_text())['records']};assert ledger['native_starts']==result['starts']==2 and ledger['provider_POST']==result['POST']==len(ledger['records'])==len(views)==31;rows=[];pins={}
 for actor in ['candidate','Both']:
  records=[x for x in ledger['records'] if x['actor']==actor];known=0;unknown=[];valid=[]
  for request in records:
   n=request['request'];raw=root/'transport'/f'response-{n}.sse';derived=root/'transport'/f'derived-response-{n}.sse';view=views[n];av=view['accounting_view'];assert sha(raw)==view['raw_sha256'] and sha(derived)==view['derived_sha256'];rebuilt=adapter.derive(events(raw),request['stream_eof'],view['provenance']);assert all(rebuilt[k]==av[k] for k in ['raw_cost','derived_cost','raw_provider_protocol_valid','correction_applied']);c=rebuilt['derived_cost']
   if c['gross_tokens'] is None:assert not c['provider_cost_complete'];unknown.append({'request':n,'provider_status':request['provider_status'],'stream_eof':request['stream_eof'],'error':request['error'],'billing_state':'UNAVAILABLE_NOT_ZERO'})
   else:c,tr=validate_response(raw,derived,request,view,adapter.derive);known+=c['gross_tokens'];valid.append(n)
   pins[str(raw.relative_to(root))]=sha(raw);pins[str(derived.relative_to(root))]=sha(derived)
  d=root/actor;native=native_events(d/'native.jsonl');term=[e['type'] for e in native if e.get('type') in ['turn.completed','turn.failed']];keys=plan['arm_recipe'][actor];actual={str(p.relative_to(d/'skills')):sha(p) for p in (d/'skills').rglob('*') if p.is_file()};assert actual=={n:h for n,h in plan['frozen_skills_manifest'].items() if n.split('/')[0] in keys};assert all((d/'prompt.txt').read_text().count((D.parent/'frozen'/k/'SKILL.md').read_text())==1 for k in keys);rows.append({'actor':actor,'POST':len(records),'complete_receipts':len(valid),'known_gross_lower_bound':known,'unknown_cost_requests':unknown,'native_terminal':term,'native_completed_usage_available':bool([e for e in native if e.get('type')=='turn.completed']),'official_grade':'0/2tests' if actor=='candidate' else 'UNAVAILABLE_CAPTURE_FAILED','actor_wall_seconds_available':actor=='candidate','capture_failure_exact_reason_known':False if actor=='Both' else None})
 cap=json.loads((root/'Both/captured/capture.json').read_text());assert cap['capture_complete'] is False and cap['artifacts']=={} and cap['error']=='unexpected member,type,name,or size';assert not (root/'Both/captured/payload-0').exists();assert rows[0]['known_gross_lower_bound']==249808 and rows[1]['known_gross_lower_bound']==197786 and [x['request'] for x in rows[1]['unknown_cost_requests']]==[31];assert not (root/'none').exists() and not (root/'K').exists();cleanup={}
 for k,args in [('containers',['docker','ps','-a','--filter','name=solpi-cf16','--format','{{.Names}}']),('networks',['docker','network','ls','--filter','name=solpi-cf16','--format','{{.Name}}'])]:cleanup[k]=subprocess.run(args,capture_output=True,text=True,check=True,timeout=10).stdout.splitlines()
 assert cleanup=={'containers':[],'networks':[]};out={'plan_sha256':digest,'terminal_partial_stage':True,'started':2,'POST':31,'receipts':31,'known_gross_lower_bound':sum(x['known_gross_lower_bound'] for x in rows),'cost_complete':False,'unknown_cost_requests':[31],'rows':rows,'unstarted':['none','K'],'cleanup':cleanup,'actual_Both_delivery_verified':True,'all_started_request_accounting_rebuilt_from_raw':True,'matched_panel_complete':False,'promotion':False,'goal_complete':False,'artifact_hashes':pins};(R/'coalesced-fasttext-failure-audit.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({k:v for k,v in out.items() if k!='artifact_hashes'},indent=2))
