"""Independentread-onlycache-phaseproof;appendnewgrade,don'trewriteoldendpoint."""
import json,pathlib,hashlib
R=pathlib.Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
if __name__=='__main__':
 plan=json.loads((R/'tex-cache-grade-phase-plan.json').read_text());result=json.loads((R/'tex-cache-grade-phase-result.json').read_text());assert result['phase_plan_sha256']==sha(R/'tex-cache-grade-phase-plan.json');assert sha(R/'run_tex_cache_grade_phase.py')==plan['runner_sha256'];assert plan['retries']==plan['actor_starts_cap']==plan['model_POST_cap']==0 and result['native_starts']==result['model_POST']==0;assert result['official_test_runs']==result['created_grader_containers']==1 and result['grade_available'] and result['cleanup_verified']
 source=pathlib.Path('/tmp/solpi-refinement-terminal-bench-2/overfull-hbox');assert all(sha(source/n)==h for n,h in plan['source_manifest'].items());saved=pathlib.Path(plan['saved_capture']);assert all(sha(saved/n)==h for n,h in plan['capture_hashes'].items());assert result['capture_hashes_after']==plan['capture_hashes'];assert all(sha(R/n)==h for n,h in plan['software_cache_manifests'].items());root=pathlib.Path(result['private_root']);assert all(sha(root/n)==h for n,h in result['artifact_hashes'].items());tests=json.loads((root/'logs/verifier/ctrf.json').read_text())['results']['tests'];assert [{'name':t['name'],'status':t['status']} for t in tests]==result['test_results'];assert {t['name'] for t in tests}==set(json.loads((R/'tex-wiring-probe.json').read_text())['collected_original_tests']);reward=(root/'logs/verifier/reward.txt').read_text().strip();assert reward==result['reward']=='0' and not result['solved'];assert sum(t['status']=='passed' for t in tests)==3;assert result['replay_hashes_verified'] and result['original_four_test_collection_verified']
 old=json.loads((R/'16k-tex-r2-result.json').read_text());repair=json.loads((R/'16k-tex-K-grade-repair.json').read_text());assert len(old['rows'])==3 and old['errors'][0]['type']=='TimeoutExpired' and not repair['grade_available'];base=json.loads((R/'16k-tex-audit.json').read_text());cost=json.loads((R/'16k-tex-ungraded-K-audit.json').read_text());assert cost['all_four_actor_costs_complete'] and cost['K_native_usage_reconciled'];rows=base['rows']+[{'arm':'K','solved':False,'reward':'0','passed_tests':3,'POST':cost['K_POST'],'gross_tokens':cost['K_gross_tokens'],'provider_cost_complete':True,'native_usage_reconciled':True,'grade_scope':'new separatelyfrozen cache-only recovery;originalendpointremainsungraded','actor_seconds':None,'old_setup_failures':2,'cache_preparation_seconds':result['cache_preparation_seconds'],'grader_seconds':result['grader_seconds']}]
 candidate=rows[0];ratios={r['arm']:candidate['gross_tokens']/r['gross_tokens'] for r in rows[1:] if r['solved']};audit={'phase_plan_sha256':result['phase_plan_sha256'],'grade_available':True,'original_endpoint_still_ungraded':True,'all_four_grades_available_across_separate_recovery_phase':True,'rows':rows,'starts':4,'POST':51,'gross_tokens':1409814,'point_ratios_against_solved_comparators':ratios,'K_verified_solve_cost_ratio':None,'K_ratio_reason':'zero verifiedsolves—notfinite orclaimedeconomywin','preparation_and_grading_recovery_failures_retained':True,'no_extra_model_calls':True,'candidate_promotion':False,'representative_confirmation':False,'goal_complete':False};(R/'tex-cache-grade-phase-audit.json').write_text(json.dumps(audit,indent=2)+'\n');print(json.dumps(audit,indent=2))
