"""Read-only selection/futility and requirement mapping; no cohort pooling."""
import pathlib,json,hashlib,subprocess,datetime
R=pathlib.Path(__file__).resolve().parent;REPO=R.parents[3];sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 stages=[];pins={}
 for name in ['feasible-first','documented-baseline','scratch-capacity','recovery-context']:
  p=R/(name+'-fasttext-audit.json');a=json.loads(p.read_text());assert a['terminal'] and a['matched_panel_complete'] and a['started']==4 and not a['unknown_cost_requests'] and a['complete_gross_tokens'] is not None and a['cleanup']=={'containers':[],'networks':[]};assert all(x['official_grade']==0 for x in a['rows']);assert a['ALL3_5percent_token_point_gate'] is None and not a['promotion'];pins[p.name]=sha(p);stages.append({'candidate':name,'plan_sha256':a['plan_sha256'],'starts':a['started'],'POST':a['POST'],'complete_gross_tokens_THIS_COHORT_ONLY':a['complete_gross_tokens'],'original_grades':{x['arm']:x['official_grade'] for x in a['rows']},'verified_solves':'0/4 in this cohort','ALL3_gate':None,'decision':'reject/no finite solve-economy ratio'})
 for n in ['source-backed-financial-audit.json','16k-regex-audit.json','behavior-first-sparql-audit.json','measured-feasibility-fasttext-audit.json']:
  pins[n]=sha(R/n)
 selection=json.loads((R/'terminal-10pct-selection.json').read_text());assert selection['selected_size']==9 and selection['full_population']==89 and selection['model']=='Qwen3.8-27B-FP8';pins['terminal-10pct-selection.json']=sha(R/'terminal-10pct-selection.json')
 check=subprocess.run(['git','diff','--exit-code','--','skills/efficient-coding'],cwd=REPO,capture_output=True,text=True);assert check.returncode==0
 criteria=[
 ('Apply optimization/reuse controls/retain negatives','supported workflow, not performance','optmization.md; latest four independent stage audits/results'),
 ('About10% representative metadata-selected subset <=3 sources','scope supported; inference limitations remain','terminal-10pct-selection.json:9/89; takeover source scope two sources, third deferred'),
 ('Only local Qwen3.8-27B for new actors','supported latest cohorts; historical heterogeneous campaigns not pooled','four phase plans and raw receipt backend audits'),
 ('Five-harness panel, >=3/5 winning','UNVERIFIED','latest scored cohorts only Codex; no current candidate confirmation in other harnesses'),
 ('At least3 benchmark families','UNVERIFIED/deferred','current two source selection; no frozen-candidate three-family confirmation'),
 ('>=5% fewer COMPLETE tokens per VERIFIED solve vsALL3/no solved-rate loss','NOT ACHIEVED','four recent cohorts0/4; sourcefinancial point-only and sourceRegex quality loss; behaviorSPARQL more tokens vsBoth/None; measuredcandidate0/Both1'),
 ('Three independently scheduled confirmation rounds','UNVERIFIED','these are separate development hypotheses, not repetitions of frozen candidate confirmation'),
 ('Paired task-cluster95% ratios below1 ALL3 and quality uncertainty','UNVERIFIED','no eligible matched solved confirmation; repeated exposed task is not independent task coverage'),
 ('Actual current Both/frozen controls/equal resource/backend/usage/failure-inclusive costs','supported for recent completed panels, not promotion','four phase plans/current inventories/exact prompts/raw-derived cost audits; missing native usage separate'),
 ('Exposed development vs sealed confirmation/network prevention','development explicitly exposed; clean confirmation eligibility UNVERIFIED','current exposed fastText cohorts; historical exposure exclusions preserved; no solution/test retrieval attribution borrowed'),
 ('USD/solve and wall/solve separately','USD UNVERIFIED; actor/setup time recorded, wall/solve undefined with zero solves','phase results/token components; cache completeness missing, no pricing assumptions'),
 ('Canonical promotion/report supported by confirmations','NOT ACHIEVED','canonical diff empty; per-phase negative reports published, not final performance report')]
 for p in [REPO/'tests/goal.md',REPO.parent/'optmization.md',REPO/'skills/efficient-coding/SKILL.md']:pins[str(p)]=sha(p)
 output={'checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'evidence review; no statistical/cohort pooling/regrading','objective':'portable canonical skill >=3/5 harness wins across3families/3rounds/ALL3paired95percent+5percent complete tokens per verified solve/noqualityloss within user local-Qwen/about10percent/<=3 source limits','separate_negative_cohorts':stages,'requirement_checklist':[{'requirement':r,'status':s,'evidence_or_gap':e} for r,s,e in criteria],'selection_decision':'No promotable candidate. Stop automatic variations of the same coalesced fastText lineage; association-only diagnostics are insufficient justification for another scored panel.','next_work':'Read-only original-versus-candidate instruction overhead/adherence review across existing successful and failed tasks, with task-answer-free portable mechanism and explicit decision gate before further execution. No easier substitution, blanket budget change, or old actor retry.','missing_input_if_no_defensible_mechanism':'A materially different evidence-backed portable mechanism or explicitly approved revised experiment contract; not relaxed acceptance or borrowed grades.','no_new_model_POST':True,'new_actor_training_grading':0,'canonical_unchanged':True,'artifact_hashes':pins,'promotion':False,'goal_complete':False};(R/'candidate-decision-review.json').write_text(json.dumps(output,indent=2)+'\n');print(json.dumps({k:v for k,v in output.items() if k not in ['artifact_hashes','requirement_checklist']},indent=2))
if __name__=='__main__':main()
