"""Offlinegateaudit;literalFAKEusage NOTperformance/nativebilling proof."""
import json,pathlib,hashlib
from audit_16k_tex import events
from prospective_output_budget import module
R=pathlib.Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
if __name__=='__main__':
 plan=json.loads((R/'failure-cell-integration-r3-plan.json').read_text());v=json.loads((R/'failure-cell-integration-r3-result.json').read_text());assert v['plan_sha256']==sha(R/'failure-cell-integration-r3-plan.json') and v['passed'];assert v['seconds']<plan['seconds_cap']==30 and v['real_model_POST']==v['native_scored_grader_gold_runs']==0;root=pathlib.Path(plan['root']);assert all(sha(root/n)==h for n,h in v['artifact_hashes'].items());assert all(sha(R/n)==h for n,h in plan['source_hashes'].items());D=R.parent/'development/pi-takeover-qwen-coalesced-verification-admission-16k/runtime';assert all(sha(D/n)==h for n,h in plan['runtime_hashes'].items());strict=module('gate_strict',(D/'usage_normalization.py').read_text());costs=module('gate_cost',(D/'provider_cost.py').read_text().replace('from usage_normalization import normalize_request',''),{'normalize_request':strict.normalize_request});adapter=module('gate_adapter',(D/'reasoning_adapter.py').read_text().replace('from provider_cost import normalize_cost',''),{'normalize_cost':costs.normalize_cost,'__file__':str(D/'reasoning_adapter.py')});forwarded=0
 for name in ['complete','expired']:
  row=json.loads((root/name/'partial-row.json').read_text());diag=json.loads((root/name/'capture-rejections.json').read_text());assert row['failure']['type']=='CaptureError' and not row['official_grade_available'] and row['teardown_complete'] and len(row['accounting_after_teardown']['rows'])==1;assert diag[0]['reason']=='size_cap' and not diag[0]['payload_read'] and not (root/name/'payload').exists()
  d=root/name;ledger=json.loads((d/'transport/ledger.json').read_text());views=json.loads((d/'transport/prospective-ledger.json').read_text())['records'];assert ledger['provider_POST']==len(ledger['records'])==len(views)==1;forwarded+=1;r=ledger['records'][0];view=views[0];raw=d/'transport/response-1.sse';derived=d/'transport/derived-response-1.sse';assert sha(raw)==view['raw_sha256'] and sha(derived)==view['derived_sha256'];rebuilt=adapter.derive(events(raw),r['stream_eof'],view['provenance']);assert all(rebuilt[k]==view['accounting_view'][k] for k in ['raw_cost','derived_cost','raw_provider_protocol_valid','correction_applied']);c=rebuilt['derived_cost'];assert v[name]['cleanup_verified'] and v[name]['deadline_epoch_and_POST_conserved'] and v[name]['gate']['extra_POST']==0
  if name=='complete':assert v[name]['gate']['drained'] and r['stream_eof'] and c['provider_cost_complete'] and c['gross_tokens']==8 and raw.read_bytes()==derived.read_bytes()
  else:assert not v[name]['gate']['drained'] and not c['provider_cost_complete'] and c['gross_tokens'] is None and v[name]['synthetic_gross_usage_NOTbilling'] is None
 assert forwarded==plan['fake_POST_cap']==2
 audit={'passed':True,'fake_exchanges':2,'real_model_POST':0,'usage_rebuilt_from_raw':True,'complete_synthetic_gross_NOTbilling':8,'expired_synthetic_gross':'UNAVAILABLE_NOT_ZERO','original_runtime_hashes_unchanged':True,'cleanup_verified':True,'native_or_real_actor_stop_tested':False,'actual_capture_exception_raised_in_controller_tested':True,'scope_limit':'standalonefuturecontrollercell/actualCaptureError/HTTPconsumerdisconnection;NOTDockeractorstop/fullscoredcontrollerdeployment','historical_cost_recovered':False,'goal_complete':False};(R/'failure-cell-integration-r3-audit.json').write_text(json.dumps(audit,indent=2)+'\n');print(json.dumps(audit,indent=2))
