"""New large native SDK request gate;synthetic upstream,zero real model calls."""
import pathlib
R=pathlib.Path(__file__).resolve().parent
code=(R/'run_prospective_native_probe.py').read_text()
def replace(old,new):
 global code
 if code.count(old)!=1:raise RuntimeError('capacity probe replacement not unique '+old[:70])
 code=code.replace(old,new)
replace('from prospective_broker_session import ProspectiveSession',"import sys\nsys.path.insert(0,str(pathlib.Path(__file__).resolve().parent.parent/'development/pi-takeover-qwen-incremental-coverage/runtime'))\nfrom prospective_body_capacity import factory,BODY_CAP\nfrom private_rejection_journal import RejectionJournal\nfrom prospective_broker_session import ProspectiveSession")
replace("root=pathlib.Path('/tmp/solpi-native-derived-'+uuid.uuid4().hex[:10])","root=pathlib.Path('/tmp/solpi-native-capacity-v2-'+uuid.uuid4().hex[:10])")
replace("root.mkdir(mode=0o700);prefix=root.name", "root.mkdir(mode=0o700);proxy_runtime=root/'proxy-runtime';proxy_runtime.mkdir(mode=0o700);expected_proxy=json.loads((R/'matched-cython-plan.json').read_text())['runtime_hashes']['stream_proxy.py'];proxy_source=(D/'runtime/stream_proxy.py').read_text();assert hashlib.sha256(proxy_source.encode()).hexdigest()==expected_proxy;assert proxy_source.count('if not 0<=n<=262144:self.send_error(413);return')==1;(proxy_runtime/'stream_proxy.py').write_text(proxy_source.replace('if not 0<=n<=262144:self.send_error(413);return','if not 0<=n<=8388608:self.send_error(413);return'));(proxy_runtime/'server.py').write_bytes((D/'runtime/server.py').read_bytes());prefix=root.name")
replace("'-v',str(D)+':/app:ro','--entrypoint','python3',S.IMAGE,'/app/runtime/stream_proxy.py'", "'-v',str(proxy_runtime)+':/app:ro','--entrypoint','python3',S.IMAGE,'/app/stream_proxy.py'")
replace("handler=type('SyntheticHandler',(B.PostHandler,),{'session':session});server=B.OwnedUnixServer(str(sock),handler)","journal=RejectionJournal(root/'local-rejections.json');expected=json.loads((R/'matched-cython-plan.json').read_text())['runtime_hashes']['server.py'];capacity=factory(D/'runtime/server.py',expected,journal);handler=type('CapacityHandler',(capacity.PostHandler,),{'session':session});server=capacity.OwnedUnixServer(str(sock),handler)")
replace("(root/'prompt.txt').write_text('Synthetic SDK transport probe. Reply ACK only. Do not use tools or inspect files.');argv=A.argv('codex',8000,root)","(root/'prompt.txt').write_text('Synthetic large-body SDK transport probe. Reply ACK only. Do not use tools or inspect files. Synthetic inert padding follows: '+('z'*300000));argv=A.argv('codex',8000,root);argv[-1]='-'")
replace("args=['create','--pull=never','--name',name", "args=['create','-i','--pull=never','--name',name")
replace("result=subprocess.run(['docker','start','-a',name],stdout=out,stderr=subprocess.STDOUT,timeout=60)","result=subprocess.run(['docker','start','-a','-i',name],input=(root/'prompt.txt').read_bytes(),stdout=out,stderr=subprocess.STDOUT,timeout=60)")
replace("assert server.workers==0;session.finish(True);events=[]", "assert server.workers==0;session.finish(True)\n  import http.client,socket\n  class LocalHTTP(http.client.HTTPConnection):\n   def connect(self):self.sock=socket.socket(socket.AF_UNIX,socket.SOCK_STREAM);self.sock.settimeout(5);self.sock.connect(str(sock))\n  client=LocalHTTP('private',timeout=5)\n  try:\n   client.request('POST','/v1/responses',body=b'',headers={'Content-Length':str(BODY_CAP+1)});reject_response=client.getresponse();report['overcap_status']=reject_response.status;reject_response.read()\n  finally:client.close()\n  report['private_rejections']=json.loads((root/'local-rejections.json').read_text())['records'];report['upstream_body_bytes']=len(calls[0][2]) if calls else 0;report['body_crossed_old_cap']=report['upstream_body_bytes']>262144;report['capacity_source_sha256']=capacity.source_sha256;report['capacity_derived_sha256']=capacity.derived_sha256;events=[]")
replace("report['worker_exited'];(R/'prospective-native-probe.json')", "report['worker_exited'] and report.get('body_crossed_old_cap') and report.get('overcap_status')==413 and len(report.get('private_rejections',[]))==1 and report['private_rejections'][0]['provider_POST']==0;(R/'capacity-native-probe.json')")
compile(code,'capacity-native-generated','exec')
if __name__=='__main__':exec(compile(code,'capacity-native-generated','exec'),{'__name__':'__main__','__file__':str(__file__)})
