"""DisconnectedrealpublicCP311grader software;no classifier/answers installed."""
import pathlib,json
import cached_grader_setup as base
from prospective_output_budget import module
R=pathlib.Path(__file__).resolve().parent

def inputs():
 x=json.loads((R/'fasttext-public-grader-cache.json').read_text());assert x['prepared'];root=pathlib.Path(x['root']);wheels=root/'wheels';assert {p.name:base.sha(p) for p in wheels.iterdir()}=={n:v['sha256'] for n,v in x['artifacts'].items()};runtime=pathlib.Path(x['python']['root']);assert {str(p.relative_to(runtime)):base.sha(p) for p in runtime.rglob('*') if p.is_file() and not p.is_symlink()}==x['python']['files'];links={str(p.relative_to(runtime)):str(p.readlink()) for p in runtime.rglob('*') if p.is_symlink()};assert links==x['python']['links'];assert all(p.resolve().is_relative_to(runtime.resolve()) for p in runtime.rglob('*') if p.is_symlink());uv=pathlib.Path(x['uv_reused']);assert base.sha(uv/'uv')=='d3dc3ca8e29337dd602a9a4df9e6edb15ebc52aed91461debeedb96939dc4ce0' and base.sha(uv/'uvx')=='421b1bb58429180a04ade98da066b5a5b6763e8ed74edef97359701c4cb42db8';return {'software_scope':x['scope'],'uv_root':str(uv),'python_root':str(runtime),'mounts':[str(wheels)+':/opt/public-wheels:ro'],'wheel_hashes':{n:v['sha256'] for n,v in x['artifacts'].items()},'setup_module_sha256':base.sha(pathlib.Path(__file__)),'public_software_manifest_sha256':base.sha(R/'fasttext-public-grader-cache.json')}
source=(R/'cached_grader_setup.py').read_text().replace('3.13.7','3.11.14').replace('python3.13','python3.11').replace('-p 3.13','-p 3.11');old='-w pytest-json-ctrf==0.3.5 pytest --version';assert source.count(old)==1;source=source.replace(old,'-w pytest-json-ctrf==0.3.5 -w scikit-learn==1.7.0 -w fasttext-wheel==0.9.2 -w numpy==1.24.0 pytest --version');private=module('fasttext_public_preload',source,{'__file__':str(R/'cached_grader_setup.py')});private.inputs=inputs;prepare=private.prepare;grade_argv=private.grade_argv;ENV=private.ENV
