"""ONE successful-recovery context retention clause; separate, unscored."""
import pathlib,json,hashlib
R=pathlib.Path(__file__).resolve().parent;C=R.parent/'candidates';P=C/'coalesced-verification/efficient-coding/SKILL.md';Q=C/'recovery-context/efficient-coding/SKILL.md'
OLD='- Apply the necessary change with its required checks in one tool or shell call when they can run together safely; keep labeled results and each exit status. Use the results to decide the next action. Repair failures, and rerun checks affected by later edits or unresolved evidence. Do not add a separate artifact dump or repeat a successful check just to prepare the final report; retain source-backed checks needed to establish correctness.'
CLAUSE='When reusing a successful recovery, preserve its relevant checked execution conditions in dependent calls without widening scope or permissions; recheck if the context changes. '
NEW=OLD.replace('Do not add a separate artifact dump',CLAUSE+'Do not add a separate artifact dump')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert not Q.exists();s=P.read_text();assert s.count(OLD)==1 and sha(P)=='cff132600efdd10e64ec47283e164be66c0992ce1d610ce442f6715a705aad87';Q.parent.mkdir(parents=True);Q.write_text(s.replace(OLD,NEW));m={'parent_sha256':sha(P),'candidate_sha256':sha(Q),'parent_words':len(s.split()),'candidate_words':len(Q.read_text().split()),'changed_bullets':1,'mechanism':'checkedsuccessfulrecovery-contextretentionfordependentcalls','separate_from_scratch_defaults_feasible_measured_byte_branches':True,'existing_checks_scope_and_safeguards_preserved':True,'evidence':'../../pi-takeover/recovery-condition-retention-audit.json','evidence_association_not_controlled_causality':True,'no_scope_permission_widening':True,'frozen':False,'scored':False,'model_POST':0,'promotion':False,'goal_complete':False};(Q.parent.parent/'draft-manifest.json').write_text(json.dumps(m,indent=2)+'\n');(Q.parent.parent/'README.md').write_text('# Recovery context — unfrozen, unscored\n\nONE clause in necessary-change/verification bullet: carry relevant checked conditions of a successful recovery into dependent later calls; recheck changed context, never widen scope/permissions. Separate coalesced descendant, not bundled with scratch, defaults, resources, parallelism or wait rules. Original required checks, per-command status, scope, reversible behavior, irreversible safeguards and final sources remain unchanged. No task names/paths/parameters, environment variable names, thread counts, budgets or native extension.\n\nTrace evidence: failed similar reads, successful explicitly conditioned read, failure when condition omitted, success when restored. Similar not identical commands and uncontrolled active processes preclude causal attribution; no claim every retained setting is necessary. Historical original grade stays 0; context retention does not ensure quality or savings. See ../../pi-takeover/recovery-condition-retention-audit.json. No polling-only successor inferred from failed longer-wait comparator.\n\nUnfrozen/unscored/no actor/promotion/economy claim. Any later screen requires a justified separately declared bounded new-candidate lineage/current Both, unchanged limits/local Qwen/original grading, failure-inclusive costs and no old retries, substitutions, budget raises, pooling or repeated unchanged controls. Longer text is not token savings. Canonical unchanged; goal incomplete.\n');print(json.dumps(m,indent=2))
if __name__=='__main__':main()
