"""ONE separate portable API-baseline hypothesis; not frozen or scored."""
import pathlib,hashlib,json
R=pathlib.Path(__file__).resolve().parent;C=R.parent/'candidates';P=C/'coalesced-verification/efficient-coding/SKILL.md';Q=C/'documented-baseline/efficient-coding/SKILL.md'
OLD='- Once a plausible approach is clear, make a small reversible, end-to-end change and inspect its actual behavior. Use that evidence to refine the change rather than exhaustively debating hypothetical cases before producing anything. For irreversible actions, check the required safeguards first; do not weaken final acceptance or verification.'
NEW='- For an existing tool or library, start from its documented idiomatic baseline; override defaults only to meet requirements or respond to observed evidence. Once a plausible approach is clear, make a small reversible, end-to-end change and inspect its actual behavior. Use that evidence to refine the change rather than exhaustively debating hypothetical cases before producing anything. For irreversible actions, check the required safeguards first; do not weaken final acceptance or verification.'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert not Q.exists(),'preserve existing draft, no silent overwrite';s=P.read_text();assert s.count(OLD)==1 and sha(P)=='cff132600efdd10e64ec47283e164be66c0992ce1d610ce442f6715a705aad87';Q.parent.mkdir(parents=True);Q.write_text(s.replace(OLD,NEW));manifest={'parent_sha256':sha(P),'candidate_sha256':sha(Q),'parent_words':len(s.split()),'candidate_words':len(Q.read_text().split()),'exact_one_bullet_replacement':True,'separate_from_feasible_measured_byte_hypotheses':True,'evidence':'../../pi-takeover/existing-api-defaults-audit.json','associational_lexical_evidence_not_causal':True,'defaults_subject_to_requirements_and_observed_evidence':True,'frozen':False,'scored':False,'model_POST':0,'promotion':False,'goal_complete':False};(Q.parent.parent/'draft-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');(Q.parent.parent/'README.md').write_text('# Documented baseline — unfrozen, unscored\n\nONE existing-tool/library baseline clause in early behavior bullet, branching from coalesced verification, not combined with failed successors. Prefer documented idiomatic baseline; permit required or evidence-backed overrides. All original behavior iteration, irreversible safeguards, final sources and required checks remain unchanged. No task names, paths, training parameters, formulas, thresholds, budgets, resource/log rules or native extensions.\n\nExisting traces show speculative nondefault choices and no matched explicit help/source-read patterns; successful historical Both aligns with one public default. This is lexical association, not causal evidence: default alignment also appears in an unsuccessful multi-config declaration; defaults can violate requirements; declarations are not submitted configurations. Historical grades remain separate and are never borrowed. See ../../pi-takeover/existing-api-defaults-audit.json.\n\nNo freeze, actors, promotion or economy claim. A separate bounded predeclared successor panel may be prepared only if this single mechanism remains defensible. No old actor retries, easier tasks, budget increases, cohort pooling, unchanged controls or answer transfer. Skill is longer, so any claimed economy must be complete failure-inclusive tokens per original verified solve. Canonical unchanged; goal incomplete.\n');print(json.dumps(manifest,indent=2))
if __name__=='__main__':main()
