"""ONE filesystem-capacity mechanism, separate coalesced descendant, no evaluation."""
import pathlib,json,hashlib
from prepare_documented_baseline_draft import OLD
R=pathlib.Path(__file__).resolve().parent;C=R.parent/'candidates';P=C/'coalesced-verification/efficient-coding/SKILL.md';Q=C/'scratch-capacity/efficient-coding/SKILL.md'
CLAUSE='For large writes or intermediate data, check available capacity on the actual output and scratch filesystems before expensive work; free space elsewhere does not establish it. '
NEW='- '+CLAUSE+OLD[2:]
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 assert not Q.exists();s=P.read_text();assert s.count(OLD)==1 and sha(P)=='cff132600efdd10e64ec47283e164be66c0992ce1d610ce442f6715a705aad87';Q.parent.mkdir(parents=True);Q.write_text(s.replace(OLD,NEW));m={'candidate_sha256':sha(Q),'parent_sha256':sha(P),'parent_words':len(s.split()),'candidate_words':len(Q.read_text().split()),'one_early_bullet_change':True,'mechanism':'actual-output/scratch-filesystemcapacity-before-large-writes','not_combined_with_documented_feasible_measured_byte_branches':True,'original_behavior_iteration_and_all_safeguards_preserved':True,'evidence':'../../pi-takeover/declared-scratch-capacity-audit.json','provider_delivery_evidence':'../../pi-takeover/provider-visible-skill-priority-audit.json','no_cpu_thread_rule_or_native_extension':True,'frozen':False,'scored':False,'model_POST':0,'promotion':False,'goal_complete':False};(Q.parent.parent/'draft-manifest.json').write_text(json.dumps(m,indent=2)+'\n');(Q.parent.parent/'README.md').write_text('# Scratch capacity — unfrozen, unscored\n\nONE capacity-check clause before large writes/intermediate-data work; distinguish actual output/scratch filesystems from free capacity elsewhere. Separate coalesced descendant; not bundled with defaults, feasibility, byte/log or CPU/parallelism rules. Exact original iteration, irreversible safeguards, source validation, scope and required final checks remain. No task names, paths, mount sizes, formulas, model configuration, budgets or answers.\n\nFrozen controller specifies bounded scratch mount. Completed traces retain preprocessing/sort ENOSPC; failed sort then printed zero counts. Candidate checked a different filesystem and reported a temporary file at declared mount capacity. Candidate exact ENOSPC causality is not established; no recreation/probes/training or repair. No skill subsequently saved a valid-size target but failed original accuracy, so capacity management alone is not proven sufficient. Actual full skills persist in provider requests; lack of delivery is not explanation. Read bounded audits under ../../pi-takeover/.\n\nUnfrozen/unscored/no promotion/economy claim. Only a justified separately predeclared bounded new-candidate lineage with exact current Both may later be tested. No actor retries, easier tasks, budget changes, prior-grade borrowing/cohort pooling, native extensions or repeated unchanged controls. Longer skill is not token savings; complete failure-inclusive cost per original verified solve remains necessary. Canonical unchanged; goal incomplete.\n');print(json.dumps(m,indent=2))
if __name__=='__main__':main()
