"""Freezeoneprivate16Kdevelopmentruntime;no model/server/graderexecution."""
import json,pathlib,shutil,hashlib
from prospective_output_budget import build,digest,R
PARENT=R.parent/'development/pi-takeover-qwen-source-backed-verification'
DEST=R.parent/'development/pi-takeover-qwen-source-backed-16k'
def files(p):return {str(f.relative_to(p)):digest(f) for f in sorted(p.rglob('*')) if f.is_file() and '__pycache__' not in f.parts}
if __name__=='__main__':
 plan=json.loads((R/'source-backed-doom-plan.json').read_text());runtime=PARENT/'runtime';assert files(runtime)==plan['runtime_hashes'];assert not DEST.exists();m=build(runtime,plan['runtime_hashes'],digest(R/'prospective_reasoning_adapter.py'),digest(R/'prospective_sse_bridge.py'))
 DEST.mkdir(mode=0o700);shutil.copytree(PARENT/'frozen',DEST/'frozen');shutil.copytree(runtime,DEST/'runtime',ignore=shutil.ignore_patterns('__pycache__','*.pyc'))
 target=DEST/'runtime';(target/'output_policy.py').write_text(m['policy'].derived_source);(target/'provider_cost.py').write_text('from usage_normalization import normalize_request\n'+m['cost'].derived_source)
 (target/'reasoning_adapter.py').write_text('from provider_cost import normalize_cost\n'+m['adapter'].derived_source);(target/'sse_bridge.py').write_text('from reasoning_adapter import derive\n'+m['bridge'].derived_source)
 broker=(R/'prospective_broker_session.py').read_text();assert broker.count('from prospective_sse_bridge import SSEBridge')==1;broker=broker.replace('from prospective_sse_bridge import SSEBridge','from sse_bridge import SSEBridge').replace('qwen-dflash-derived-receipts-draft-v1','qwen-dflash-16k-derived-receipts-v1');(target/'broker_session.py').write_text(broker)
 panel=(R/'matched_html_support.py').read_text();assert panel.count('from prospective_broker_session import ProspectiveSession')==1 and panel.count('from prospective_reasoning_adapter import SOURCE_PINS,SOURCE,MODEL')==1;panel=panel.replace('from prospective_broker_session import ProspectiveSession','from broker_session import ProspectiveSession').replace('from prospective_reasoning_adapter import SOURCE_PINS,SOURCE,MODEL','from reasoning_adapter import SOURCE_PINS,SOURCE,MODEL');(target/'budget_panel.py').write_text(panel)
 for f in target.glob('*.py'):compile(f.read_text(),str(f),'exec')
 assert files(DEST/'frozen')==plan['frozen_skills_manifest'];assert files(runtime)==plan['runtime_hashes']
 manifest={'parent':str(PARENT),'candidate_sha256':digest(DEST/'frozen/candidate/SKILL.md'),'frozen_manifest':files(DEST/'frozen'),'runtime_hashes':files(target),'arm_recipe':{'none':[],'K':['karpathy'],'candidate':['candidate'],'Both':['karpathy','candidate']},'comparator_Both_definition':'currentcandidate+frozenKarpathy','configured_output_cap':16384,'only_existing_runtime_changes':['output_policy.py','provider_cost.py'],'new_runtime_modules':['reasoning_adapter.py','sse_bridge.py','broker_session.py','budget_panel.py'],'same_candidate_no_new_hypothesis':True,'parent_runtime_hashes':plan['runtime_hashes'],'source_module_hashes':{name:digest(R/name) for name in ['prepare_16k_runtime.py','prospective_output_budget.py','prospective_reasoning_adapter.py','prospective_sse_bridge.py','prospective_broker_session.py','matched_html_support.py']},'task':'overfull-hbox','stage':'development/notsealedconfirmation','model':'Qwen3.8-27B-FP8','peer':'127.0.0.1:18001','model_effort_change':False,'shared_server_changes':False,'actor_starts':0,'model_POST':0,'integration_verified':False,'canonical_promotion':False,'goal_complete':False};(DEST/'freeze-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');print(json.dumps({'private_runtime':str(DEST),'freeze_sha256':digest(DEST/'freeze-manifest.json'),'existing_runtime_changes':[n for n,h in plan['runtime_hashes'].items() if files(target)[n]!=h]},indent=2))
