"""Genericsoftware/layout/collectionONLY;reusecontrols/no realmodel/gold/test runs."""
import hashlib,json,pathlib,subprocess,uuid
from sparql_public_inputs import recipe,cache
from actor_public_inputs import docker_options
from sparql_output_presence import stopped_output_present
from task_artifacts import capture_stopped_actor
from artifact_capture import CaptureError
from sparql_grader_setup import inputs,prepare,ENV
R=pathlib.Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
if __name__=='__main__':
 assert not (R/'sparql-readiness-probe.json').exists();spec=recipe('sparql-university');image=spec['actor_image_id'];assert image==spec['grader_image_id'];transfer=json.loads((R/'file-capture-sparql-university-result.json').read_text());assert transfer['valid_output_replay'] and transfer['cleanup_verified'] and transfer['same_test_collection'];root=pathlib.Path('/tmp/solpi-sparql-readiness-'+uuid.uuid4().hex[:10]);root.mkdir(mode=0o700);owned=[];out={'task':'sparql-university','root':str(root),'official_test_runs':0,'gold_runs':0,'scored_actor_starts':0,'model_POST':0,'positive_controls_and_transfer_reused_not_run':True,'public_recipe':spec}
 def docker(*args,timeout=20):return subprocess.check_output(['docker',*args],stderr=subprocess.STDOUT,text=True,timeout=timeout).strip()
 try:
  name=root.name+'-layout';owned.append(name);docker('create','--name',name,'--network','none','--cap-drop','ALL','--security-opt','no-new-privileges','--entrypoint','/bin/sh',image,'-c','sleep infinity');assert not stopped_output_present(name,image);out['real_stopped_absence_verified']=True;directory=root/'solution.sparql';directory.mkdir();docker('cp',str(directory),name+':/app/solution.sparql');assert stopped_output_present(name,image)
  try:capture_stopped_actor('sparql-university',name,image,root/'unsupported');raise AssertionError('directorycaptureaccepted')
  except CaptureError:out['unsupported_directory_not_quality_zero']=True
  docker('rm',name);owned.remove(name);name=root.name+'-file';owned.append(name);docker('create','--name',name,'--network','none','--cap-drop','ALL','--security-opt','no-new-privileges','--entrypoint','/bin/sh',image,'-c','sleep infinity');sentinel=root/'generic-sentinel';sentinel.write_text('GENERIC_TRANSPORT_ONLY_NOT_TASK_QUERY\n');docker('cp',str(sentinel),name+':/app/solution.sparql');assert stopped_output_present(name,image);cap=capture_stopped_actor('sparql-university',name,image,root/'captured');assert cap['artifacts']['/app/solution.sparql']['sha256']==sha(sentinel);out['generic_regular_capture_verified']=True
  name=root.name+'-public';owned.append(name);args=['create','--name',name,'--network','none','--cap-drop','ALL','--security-opt','no-new-privileges','--cpus','1','--memory','2048m',*docker_options(spec),'--entrypoint','/bin/sh',image,'-c',"set -eu; python3 --version; python3 -c 'import rdflib; print(rdflib.__version__); g=rdflib.Graph(); g.parse(data=\"<urn:a> <urn:p> <urn:b> .\",format=\"turtle\"); assert len(list(g.query(\"SELECT ?s WHERE {?s ?p ?o}\")))==1'; test ! -e /app/solution.sparql; sha256sum /app/university_graph.ttl"];docker(*args);text=docker('start','-a',name,timeout=30);meta=json.loads(docker('inspect',name))[0];assert meta['State']['ExitCode']==0 and len(meta['Mounts'])==2 and all(not m['RW'] for m in meta['Mounts']);assert 'Python 3.13.7' in text and '7.1.4' in text;graph_hash=text.splitlines()[-1].split()[0];assert graph_hash==sha(pathlib.Path('/tmp/solpi-refinement-terminal-bench-2/sparql-university/environment/university_graph.ttl'));out.update(public_python_RDF_software_verified=True,public_software_only_graph_fixture_not_task_query=True,original_graph_sha256=graph_hash)
  name=root.name+'-collect';owned.append(name);logs=root/'logs';(logs/'verifier').mkdir(parents=True);args=['create','--name',name,'--network','none','--cpus','1','--memory','2048m','--security-opt','no-new-privileges','-v','/tmp/solpi-refinement-terminal-bench-2/sparql-university/tests:/tests:ro','-v',str(logs)+':/logs:rw'];
  for mount in inputs()['mounts']:args+=['-v',mount]
  docker(*args,'--entrypoint','/bin/sh',image,'-c','sleep infinity');docker('start',name);out['software_setup']=prepare(name,image,root);text=docker('exec','-w','/app',*ENV,name,'/root/.local/bin/uvx','-p','3.13','-w','pytest==8.4.1','-w','rdflib==7.1.4','-w','pytest-json-ctrf==0.3.5','pytest','--collect-only','-q','/tests/test_outputs.py',timeout=60);(root/'collection.log').write_text(text+'\n');names=[l.strip() for l in text.splitlines() if '::test_' in l];assert names==[t['name'] for t in transfer['replay']['tests']];out['collected_original_tests']=names;assert docker('exec',name,'sha256sum','/app/university_graph.ttl').split()[0]==graph_hash;out['trusted_original_graph_verified']=True;out['passed']=True
 except Exception as e:out.update(passed=False,error={'type':type(e).__name__,'message':str(e)[:500]})
 finally:
  for name in owned:subprocess.run(['docker','rm','-f',name],capture_output=True,timeout=30)
  out['cleanup_verified']=all(subprocess.run(['docker','inspect',name],capture_output=True,timeout=10).returncode!=0 for name in owned);src=pathlib.Path('/tmp/solpi-refinement-terminal-bench-2/sparql-university');out['source_manifest']={str(p.relative_to(src)):sha(p) for p in src.rglob('*') if p.is_file()};out['artifact_hashes']={str(p.relative_to(root)):sha(p) for p in root.rglob('*') if p.is_file()};(R/'sparql-readiness-probe.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({k:v for k,v in out.items() if k not in ['source_manifest','artifact_hashes']},indent=2))
