"""Publicsoftwareimport+originalcollectionONLY;no training/data/target/gold/tests."""
import pathlib,json,uuid,subprocess
from actor_public_inputs import recipe,docker_options
from fasttext_grader_setup import inputs,prepare,ENV
R=pathlib.Path(__file__).resolve().parent
if __name__=='__main__':
 assert not (R/'fasttext-cached-software-probe.json').exists();root=pathlib.Path('/tmp/solpi-fasttext-software-'+uuid.uuid4().hex[:10]);root.mkdir(mode=0o700);owned=[];spec=recipe('train-fasttext');image=spec['actor_image_id'];out={'root':str(root),'model_POST':0,'scored_actor_starts':0,'models_trained':0,'official_test_runs':0,'gold_runs':0,'scope':'importABI/publicversions/originalcollectiononly;no model/dataset read'}
 def docker(*args,timeout=30):return subprocess.check_output(['docker',*args],stderr=subprocess.STDOUT,text=True,timeout=timeout).strip()
 try:
  name=root.name+'-actor-software';owned.append(name);docker('create','--name',name,'--network','none','--cap-drop','ALL','--security-opt','no-new-privileges','--cpus','1','--memory','4096m',*docker_options(spec),'--entrypoint','/bin/sh',image,'-c',"set -eu; test ! -e /app/model.bin; python -m pip install --no-index --find-links=/opt/public-wheels -r /opt/public-requirements.txt; python -c 'import fasttext,numpy,importlib.metadata; print(importlib.metadata.version(\"fasttext\")); print(numpy.__version__)'; test ! -e /app/model.bin");text=docker('start','-a',name,timeout=90);(root/'actor-software.log').write_text(text+'\n');meta=json.loads(docker('inspect',name))[0];assert meta['State']['ExitCode']==0 and all(not m['RW'] for m in meta['Mounts']);out['actor_public_dependencies_imported']=True
  name=root.name+'-grader';owned.append(name);args=['create','--name',name,'--network','none','--cpus','1','--memory','4096m','--security-opt','no-new-privileges','-v','/tmp/solpi-refinement-terminal-bench-2/train-fasttext/tests:/tests:ro']
  for m in inputs()['mounts']:args+=['-v',m]
  docker(*args,'--entrypoint','/bin/sh',image,'-c','sleep infinity');docker('start',name);out['setup']=prepare(name,image,root);text=docker('exec',*ENV,name,'/root/.local/bin/uvx','-p','3.11','-w','pytest==8.4.1','-w','scikit-learn==1.7.0','-w','fasttext-wheel==0.9.2','-w','numpy==1.24.0','-w','pytest-json-ctrf==0.3.5','python','-c','import fasttext,numpy,sklearn,importlib.metadata,sys; assert numpy.__version__=="1.24.0"; assert sklearn.__version__=="1.7.0"; assert importlib.metadata.version("fasttext-wheel")=="0.9.2"; assert sys.version.startswith("3.11.14"); print("PINNED_PUBLIC_IMPORTS_OK")');assert text=='PINNED_PUBLIC_IMPORTS_OK';out['grader_pinned_versions_imported']=True
  text=docker('exec',*ENV,'-w','/app',name,'/root/.local/bin/uvx','-p','3.11','-w','pytest==8.4.1','-w','scikit-learn==1.7.0','-w','fasttext-wheel==0.9.2','-w','numpy==1.24.0','-w','pytest-json-ctrf==0.3.5','pytest','--collect-only','-q','/tests/test_outputs.py');(root/'collection.log').write_text(text+'\n');names=[l.strip() for l in text.splitlines() if '::test_' in l];transfer=json.loads((R/'file-capture-train-fasttext-result.json').read_text());assert transfer['valid_output_replay'] and transfer['cleanup_verified'];assert names==[x['name'] for x in transfer['replay']['tests']];out['collected_original_tests']=names;docker('exec',name,'/bin/sh','-c','test ! -e /app/model.bin');out['original_target_still_absent']=True;out['passed']=True
 except Exception as e:out.update(passed=False,error={'type':type(e).__name__,'message':str(e)[:1000]})
 finally:
  for name in owned:subprocess.run(['docker','rm','-f',name],capture_output=True,timeout=30)
  out['cleanup_verified']=all(subprocess.run(['docker','inspect',n],capture_output=True,timeout=10).returncode!=0 for n in owned);(R/'fasttext-cached-software-probe.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
