"""Reusecompletedbinarycapture;newgrader-onlyfixedreplayinvocation+tarwiring."""
import pathlib,json,uuid,subprocess,shutil,hashlib
from actor_public_inputs import recipe
from fasttext_grader_setup_r2 import inputs,prepare,ENV
from task_replay import replay_capture,verify_payload
R=pathlib.Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def files(root):return {str(p.relative_to(root)):sha(p) for p in root.rglob('*') if p.is_file()}
if __name__=='__main__':
 assert not (R/'fasttext-readiness-probe-r2.json').exists();old=json.loads((R/'fasttext-readiness-probe.json').read_text());assert old['stopped_absence_verified'] and old['directory_rejected_not_qualityzero'] and old['regular_binary_capture_verified'] and old['cleanup_verified'];prior=pathlib.Path(old['root']);cap=json.loads((prior/'captured/capture.json').read_text());verify_payload(prior/'captured/payload-0',cap['artifacts']['/app/model.bin']);source=pathlib.Path('/tmp/solpi-refinement-terminal-bench-2/train-fasttext/tests');before=files(source);root=pathlib.Path('/tmp/solpi-fasttext-wiring-r2-'+uuid.uuid4().hex[:10]);root.mkdir(mode=0o700);grader=root.name+'-grader';image=recipe('train-fasttext')['grader_image_id'];out={'root':str(root),'task':'train-fasttext','model_POST':0,'scored_actor_starts':0,'models_trained':0,'official_test_runs':0,'gold_runs':0,'completed_capture_proof_reused':True,'first_wiring_failure_sha256':sha(R/'fasttext-readiness-probe.json'),'stopped_absence_verified':True,'directory_rejected_not_qualityzero':True,'regular_binary_capture_verified':True}
 def docker(*a,timeout=30):return subprocess.check_output(['docker',*a],stderr=subprocess.STDOUT,text=True,timeout=timeout).strip()
 try:
  tests=root/'trusted-tests-copy';shutil.copytree(source,tests);assert files(tests)==before;logs=root/'logs';(logs/'verifier').mkdir(parents=True);args=['create','--name',grader,'--network','none','--cpus','1','--memory','4096m','--security-opt','no-new-privileges','-v',str(tests)+':/tests:rw','-v',str(logs)+':/logs:rw']
  for m in inputs()['mounts']:args+=['-v',m]
  docker(*args,'--entrypoint','/bin/sh',image,'-c','sleep infinity');docker('start',grader);out['replay']=replay_capture('train-fasttext',capture_root=prior/'captured',container=grader,image_id=image);out['setup']=prepare(grader,image,root);docker('exec',grader,'tar','-xzf','/tests/private_test.tar.gz','-C','/tests');assert all(sha(tests/n)==h for n,h in before.items());out['original_test_files_unchanged_after_tar_extraction']=True;out['trusted_tar_extraction_into_private_writable_copy']=True;text=docker('exec','-w','/app',*ENV,grader,'/root/.local/bin/uvx','-p','3.11','-w','pytest==8.4.1','-w','scikit-learn==1.7.0','-w','fasttext-wheel==0.9.2','-w','numpy==1.24.0','-w','pytest-json-ctrf==0.3.5','pytest','--collect-only','-q','/tests/test_outputs.py');names=[l.strip() for l in text.splitlines() if '::test_' in l];assert names==json.loads((R/'fasttext-cached-software-probe-r2.json').read_text())['collected_original_tests'];out['collected_original_tests']=names;(root/'collection.log').write_text(text+'\n');docker('cp',grader+':/app/model.bin',str(root/'replayed-sentinel'));assert sha(root/'replayed-sentinel')==sha(prior/'sentinel');out['exact_target_only_replay_no_build_verified']=True;out['passed']=True
 except Exception as e:out.update(passed=False,error={'type':type(e).__name__,'message':str(e)[:1000]})
 finally:
  subprocess.run(['docker','rm','-f',grader],capture_output=True,timeout=30);out['cleanup_verified']=subprocess.run(['docker','inspect',grader],capture_output=True,timeout=10).returncode!=0;out['source_tests_unchanged']=files(source)==before;out['original_test_manifest']=before;out['artifact_hashes']={str(p.relative_to(root)):sha(p) for p in root.rglob('*') if p.is_file()};(R/'fasttext-readiness-probe-r2.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({k:v for k,v in out.items() if k!='artifact_hashes'},indent=2))
