"""Grade same saved partial capture;no helper rerun or target rebuild."""
import hashlib,json,pathlib,subprocess,uuid
from pmars_partial_output import replay_partial,verify_partial
from pmars_grader_setup import prepare,grade_argv
R=pathlib.Path(__file__).resolve().parent;TASK=pathlib.Path('/tmp/solpi-refinement-terminal-bench-2/build-pmars')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def docker(*args):return subprocess.run(['docker',*args],capture_output=True,text=True,check=True,timeout=60)
if __name__=='__main__':
 old=json.loads((R/'pmars-partial-transfer-probe.json').read_text());assert old['passed'];capture=pathlib.Path(old['private_root'])/'captured';image=old['capture']['image_id'];verify_partial(capture,image);root=pathlib.Path('/tmp/solpi-pmars-partial-grade-'+uuid.uuid4().hex[:10]);root.mkdir(mode=0o700);logs=root/'logs';logs.mkdir();(logs/'verifier').mkdir();name=root.name+'-grader';plan={'image_id':image,'capture_manifest_sha256':sha(capture/'capture.json'),'test_script_sha256':sha(TASK/'tests/test.sh'),'test_assertions_sha256':sha(TASK/'tests/test_outputs.py'),'setup_module_sha256':sha(R/'pmars_grader_setup.py'),'target_builds':0,'target_installs':0,'native_starts':0,'provider_POST':0,'maximum_setup_seconds':300,'maximum_original_test_seconds':600,'scope':'trusted generic publicsoftware preload thennetwork-disconnected unchangedoriginalgrader;not actorretry/skillcomparison/goldcontrol'};(root/'plan.json').write_text(json.dumps(plan,indent=2)+'\n');report={**plan,'private_root':str(root),'reused_capture':str(capture),'helper_reruns':0,'grader_calls':0}
 try:
  docker('create','--name',name,'--network','bridge','--cpus','1','--memory','2048m','--pids-limit','512','--security-opt','no-new-privileges','-v',str(TASK/'tests')+':/tests:ro','-v',str(logs)+':/logs:rw','-v','/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro','--entrypoint','/bin/sh',image,'-c','sleep infinity');report['replay']=replay_partial(capture,name,image);report['setup']=prepare(name,image,root);report['grader_calls']=1
  with (root/'verifier.log').open('wb') as out:p=subprocess.run(grade_argv(name),stdout=out,stderr=subprocess.STDOUT,timeout=600)
  tests=json.loads((logs/'verifier/ctrf.json').read_text())['results']['tests'];reward=(logs/'verifier/reward.txt').read_text().strip();report.update(verifier_exit=p.returncode,reward=reward,test_results=[{'name':t['name'],'status':t['status']} for t in tests]);assert len(tests)==4 and reward=='0' and sum(t['status']=='passed' for t in tests)==2;docker('exec',name,'test','!','-e','/usr/local/bin/pmars');text=docker('exec',name,'cat','/app/pmars-0.9.4/src/marker.c').stdout;assert hashlib.sha256(text.encode()).hexdigest()==old['source_readback_sha256'];report['source_bytes_unchanged']=True;report['target_absence_preserved']=True;assert sha(TASK/'tests/test.sh')==plan['test_script_sha256'];report['passed']=True
 except Exception as e:report['passed']=False;report['error']={'type':type(e).__name__,'message':str(e)}
 finally:
  subprocess.run(['docker','rm','-f',name],capture_output=True,timeout=30);p=subprocess.run(['docker','inspect',name],capture_output=True,text=True,timeout=10);report['cleanup_verified']=p.returncode!=0 and 'No such' in p.stderr;report['evidence_hashes']={str(p.relative_to(root)):sha(p) for p in root.rglob('*') if p.is_file()};(R/'pmars-partial-grade-probe.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))
