"""NewmissingELF/witnessseparationgate;reusepositivecontrols,no model/targetbuild."""
import hashlib,json,pathlib,subprocess,uuid
from actor_public_inputs import recipe,docker_options,verify_actor_inspect
from doom_output import capture_missing,replay_missing
from doom_grader_setup import prepare,grade_argv
R=pathlib.Path(__file__).resolve().parent;SOURCE=pathlib.Path('/tmp/solpi-refinement-terminal-bench-2/make-doom-for-mips')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def docker(*a):return subprocess.run(['docker',*a],capture_output=True,text=True,check=True,timeout=60)
if __name__=='__main__':
 root=pathlib.Path('/tmp/solpi-doom-missing-'+uuid.uuid4().hex[:10]);root.mkdir(mode=0o700);spec=recipe(SOURCE.name);actor=root.name+'-actor';grader=root.name+'-grader';owned=[];logs=root/'logs';(logs/'verifier').mkdir(parents=True);out={'private_root':str(root),'native_starts':0,'provider_POST':0,'grader_calls':0,'helper_attempts':1,'target_builds':0,'target_installs':0,'test_script_sha256':sha(SOURCE/'tests/test.sh'),'tests_sha256':sha(SOURCE/'tests/test_outputs.py'),'scope':'newmissingELF pluschangedinputwitnessnotreplayed,notgoldcontrol/transferrepeat'}
 try:
  docker('create','--name',actor,'--network','none','--cpus',str(spec['cpus']),'--memory',str(spec['memory_mb'])+'m','--pids-limit','128','--cap-drop','ALL','--security-opt','no-new-privileges',*docker_options(spec),'--entrypoint','/bin/sh',spec['actor_image_id'],'-c','sleep infinity');owned.append(actor);out['actor_isolation']=verify_actor_inspect(json.loads(docker('inspect',actor).stdout)[0],spec,'none',{});docker('start',actor);out['original_vm_sha256']=docker('exec',actor,'sha256sum','/app/vm.js').stdout.split()[0];docker('exec',actor,'/bin/sh','-c','printf "%s" "synthetic changed witness,nottrusted VM" > /app/vm.js; test ! -e /app/doomgeneric_mips');docker('stop','-t','0',actor);out['capture']=capture_missing(actor,spec['actor_image_id'],root/'captured');docker('rm',actor);owned.remove(actor)
  docker('create','--name',grader,'--network','bridge','--cpus',str(spec['cpus']),'--memory',str(spec['memory_mb'])+'m','--pids-limit','512','--security-opt','no-new-privileges','-v',str(SOURCE/'tests')+':/tests:ro','-v',str(logs)+':/logs:rw','-v','/etc/ssl/certs/ca-certificates.crt:/opt/trusted-ca.pem:ro','--entrypoint','/bin/sh',spec['grader_image_id'],'-c','sleep infinity');owned.append(grader);out['replay']=replay_missing(root/'captured',grader,spec['grader_image_id'],actor_image_id=spec['actor_image_id']);out['trusted_vm_sha256']=docker('exec',grader,'sha256sum','/app/vm.js').stdout.split()[0];assert out['trusted_vm_sha256']==out['original_vm_sha256'] and out['trusted_vm_sha256']!=out['capture']['artifacts']['/app/vm.js']['sha256'];out['setup']=prepare(grader,spec['grader_image_id'],root);out['grader_calls']=1
  with (root/'verifier.log').open('wb') as log:p=subprocess.run(grade_argv(grader),stdout=log,stderr=subprocess.STDOUT,timeout=600)
  tests=json.loads((logs/'verifier/ctrf.json').read_text())['results']['tests'];reward=(logs/'verifier/reward.txt').read_text().strip();out.update(verifier_exit=p.returncode,reward=reward,test_results=[{'name':t['name'],'status':t['status']} for t in tests]);assert len(tests)==3 and all(t['status']=='failed' for t in tests) and reward=='0';docker('exec',grader,'test','!','-e','/app/doomgeneric_mips');assert sha(SOURCE/'tests/test.sh')==out['test_script_sha256'];out['target_absence_preserved']=True;out['passed']=True
 except Exception as e:out['passed']=False;out['error']={'type':type(e).__name__,'message':str(e)}
 finally:
  for name in owned:subprocess.run(['docker','rm','-f',name],capture_output=True,timeout=30)
  out['cleanup_verified']=all(subprocess.run(['docker','inspect',n],capture_output=True,timeout=10).returncode!=0 for n in [actor,grader]);out['evidence_hashes']={str(p.relative_to(root)):sha(p) for p in root.rglob('*') if p.is_file()};out['module_hashes']={n:sha(R/n) for n in ['doom_output.py','doom_grader_setup.py','run_doom_missing_probe.py']};(R/'doom-missing-probe.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
