"""OneNEWfrozencache-onlygradingphase;oldphaseunchanged,no actor/modelretry."""
import hashlib,json,pathlib,shutil,subprocess,time,uuid
from task_replay import replay_capture,verify_payload
from task_artifacts import descriptor,GUARDS
from protected_inputs import check_protected_inputs
R=pathlib.Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
if __name__=='__main__':
 assert not (R/'tex-cache-grade-phase-plan.json').exists(),'one phaseonly'
 oldplan=json.loads((R/'16k-tex-r2-plan.json').read_text());oldsha=sha(R/'16k-tex-r2-plan.json');original=pathlib.Path('/tmp/solpi-t16-'+oldsha[:18]);saved=original/'K/captured';src=pathlib.Path('/tmp/solpi-refinement-terminal-bench-2/overfull-hbox');repair=json.loads((R/'16k-tex-K-grade-repair.json').read_text());assert not repair['grade_available'] and repair['cleanup_verified'];assert all(sha(src/n)==h for n,h in oldplan['task_source_manifest'].items());assert all(sha(R/n)==h for n,h in oldplan['prospective_module_hashes'].items());ready=json.loads((R/'tex-cached-software-preflight.json').read_text());assert ready['passed'] and ready['cleanup_verified'];inventory=json.loads((R/'tex-recovery-cache-inventory.json').read_text());cap=json.loads((saved/'capture.json').read_text());assert cap['protected_input_gate_passed'] and cap['image_id']==oldplan['actor_image_id'];assert check_protected_inputs(oldplan['protected_inputs_original'],{p:cap['artifacts'][p] for p in GUARDS['overfull-hbox']},GUARDS['overfull-hbox'])['unchanged']
 for item in descriptor('overfull-hbox'):verify_payload(saved/cap['artifacts'][item['path']]['local_payload'],cap['artifacts'][item['path']])
 pins={str(p.relative_to(saved)):sha(p) for p in saved.rglob('*') if p.is_file()};root=pathlib.Path('/tmp/solpi-tex-cache-grade-'+uuid.uuid4().hex[:10]);root.mkdir(mode=0o700);wheels=root/'wheels';wheels.mkdir();logs=root/'logs';(logs/'verifier').mkdir(parents=True)
 for rec in inventory['verified_wheels'].values():
  p=pathlib.Path(rec['path']);assert sha(p)==rec['sha256'];shutil.copyfile(p,wheels/p.name)
 expanded=pathlib.Path('/tmp/solpi-tex-public-runtime-expanded');uv=expanded/'uv/uv-x86_64-unknown-linux-gnu';python=expanded/'cpython/python';assert sha(uv/'uv')=='d3dc3ca8e29337dd602a9a4df9e6edb15ebc52aed91461debeedb96939dc4ce0';assert sha(uv/'uvx')=='421b1bb58429180a04ade98da066b5a5b6763e8ed74edef97359701c4cb42db8'
 plan={'phase':'newcacheonlygrader,replacesneitheroriginalnorrepairedattempt','authorization_basis':'standingusergoal+currentcontinueinstruction;earlierassistant-addedextraapprovalgatewasnotuserrequirement','historical_plan_sha256':oldsha,'saved_capture':str(saved),'capture_hashes':pins,'original_image_id':oldplan['image_id'],'source_manifest':oldplan['task_source_manifest'],'software_cache_manifests':{n:sha(R/n) for n in ['tex-public-runtime-archive-cache.json','tex-public-runtime-archive-inspection.json','tex-recovery-cache-inventory.json','tex-cached-software-preflight.json']},'runner_sha256':sha(pathlib.Path(__file__)),'cache_prepare_seconds_cap':90,'official_grader_containers_cap':1,'official_test_runs_cap':1,'grader_seconds_cap':600,'retries':0,'actor_starts_cap':0,'model_POST_cap':0,'network':'none throughout','original_script_unchanged':True,'standard_uv_PATH_environment_file':'export PATH=/root/.local/bin:$PATH;realpinneduvbinaries,nocurl/apt/installer-successshim','old_setup_failures_and_missing_actor_timing_retained':True,'goal_complete':False};(R/'tex-cache-grade-phase-plan.json').write_text(json.dumps(plan,indent=2)+'\n');phase_sha=sha(R/'tex-cache-grade-phase-plan.json');out={'phase_plan_sha256':phase_sha,'private_root':str(root),'native_starts':0,'model_POST':0,'official_test_runs':0,'original_setup_failures_preserved':True,'created_grader_containers':0};name=root.name;created=False;deadline=time.monotonic()+90
 def docker(*args):return subprocess.check_output(['docker',*args],stderr=subprocess.STDOUT,text=True,timeout=max(.1,deadline-time.monotonic())).strip()
 try:
  docker('create','--name',name,'--network','none','--cpus',str(oldplan['cpus']),'--memory',str(oldplan['memory_mb'])+'m','--pids-limit','512','--security-opt','no-new-privileges','-v',str(src/'tests')+':/tests:ro','-v',str(logs)+':/logs:rw','-v',str(wheels)+':/opt/public-wheels:ro','--entrypoint','/bin/sh',oldplan['image_id'],'-c','sleep infinity');created=True;out['created_grader_containers']=1
  # Genericpreflight/collectionBEFOREsubmittedoutputreplay,notgrading.
  docker('start',name);docker('exec',name,'mkdir','-p','/root/.local/bin','/root/.local/share/uv/python');docker('cp',str(uv/'uv'),name+':/root/.local/bin/uv');docker('cp',str(uv/'uvx'),name+':/root/.local/bin/uvx');docker('cp',str(python),name+':/root/.local/share/uv/python/cpython-3.13.7-linux-x86_64-gnu');docker('exec',name,'/bin/sh','-c','printf \'%s\\n\' \'export PATH="/root/.local/bin:$PATH"\' > /root/.local/bin/env')
  env=['-e','UV_OFFLINE=1','-e','UV_PYTHON_DOWNLOADS=never','-e','UV_NO_INDEX=1','-e','UV_FIND_LINKS=/opt/public-wheels'];text=docker('exec','-w','/app',*env,name,'/root/.local/bin/uvx','-p','3.13','-w','pytest==8.4.1','-w','pytest-json-ctrf==0.3.5','pytest','--collect-only','-q','/tests/test_outputs.py');(root/'collection.log').write_text(text+'\n');names=[l.strip() for l in text.splitlines() if '::test_' in l];assert set(names)==set(json.loads((R/'tex-wiring-probe.json').read_text())['collected_original_tests']) and len(names)==4;out['original_four_test_collection_verified']=True
  # Replayonlysavedinput.texafterverifyingallpayloads;existingidlecontaineralreadypublicsoftwarepreloaded.
  rec=cap['artifacts']['/app/input.tex'];docker('cp',str(saved/rec['local_payload']),name+':/app/input.tex');actual=docker('exec',name,'sha256sum','/app/input.tex','/app/main.tex','/app/synonyms.txt').splitlines();expected=[rec['sha256'],cap['artifacts']['/app/main.tex']['sha256'],cap['artifacts']['/app/synonyms.txt']['sha256']];assert [l.split()[0] for l in actual]==expected;meta=json.loads(docker('inspect',name))[0];assert meta['Image']==oldplan['image_id'] and set(meta['NetworkSettings']['Networks'])=={'none'};out['replay_hashes_verified']=True;out['cache_preparation_seconds']=90-max(0,deadline-time.monotonic());out['official_test_runs']=1;start=time.monotonic()
  with (root/'verifier.log').open('wb') as log:p=subprocess.run(['docker','exec','-w','/app',*env,name,'bash','/tests/test.sh'],stdout=log,stderr=subprocess.STDOUT,timeout=600)
  out['grader_seconds']=time.monotonic()-start;out['verifier_exit']=p.returncode;tests=json.loads((logs/'verifier/ctrf.json').read_text())['results']['tests'];reward=(logs/'verifier/reward.txt').read_text().strip();assert len(tests)==4 and {t['name'] for t in tests}==set(names) and reward in ['0','1'];out.update(grade_available=True,reward=reward,solved=reward=='1' and all(t['status']=='passed' for t in tests),test_results=[{'name':t['name'],'status':t['status']} for t in tests]);assert all(sha(src/n)==h for n,h in plan['source_manifest'].items())
 except Exception as e:out.update(grade_available=False,error={'type':type(e).__name__,'message':str(e)[:500]})
 finally:
  if created:subprocess.run(['docker','rm','-f',name],capture_output=True,timeout=30)
  out['cleanup_verified']=subprocess.run(['docker','inspect',name],capture_output=True,timeout=10).returncode!=0;out['capture_hashes_after']={str(p.relative_to(saved)):sha(p) for p in saved.rglob('*') if p.is_file()};assert out['capture_hashes_after']==pins;out['artifact_hashes']={str(p.relative_to(root)):sha(p) for p in root.rglob('*') if p.is_file()};out['goal_complete']=False;(R/'tex-cache-grade-phase-result.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
