"""Render terminal native agy stage, keeping missing accounting explicit."""
import csv,json
from pathlib import Path
OUT=Path(__file__).resolve().parent
records=json.loads((OUT/'results.json').read_text());assert len(records)==4 and all(r['official_patch_resolved'] is not None for r in records)
byarm={r['arm']:r for r in records};candidate=byarm['candidate']['reported_total_tokens'];ratios={a:100*(candidate/byarm[a]['reported_total_tokens']-1) for a in ('none','karpathy','both')}
with (OUT/'summary.csv').open('w') as f:
 writer=csv.DictWriter(f,fieldnames=['harness','arm','execution_status','solved','official_patch_resolved','reported_total_tokens','elapsed_seconds']);writer.writeheader();writer.writerows({k:r[k] for k in writer.fieldnames} for r in records)
metadata={'stage_status':'complete','benchmark':'SWE-bench Verified','task':'pallets__flask-5014','freshness':'Previously exposed development fixture, one round, not held-out confirmation','actor_starts':4,'verified_solves':sum(r['solved'] is True for r in records),'native_sdk_successes':sum(r['sdk_terminal_statuses']==['SUCCESS'] for r in records),'timeouts':sum(r['timeout'] for r in records),'auth_errors':sum(r['execution_status']=='blocked_auth_or_quota' for r in records),'actor_seconds':sum(r['elapsed_seconds'] for r in records),'requested_model':'gemini-3.8-flash-low','observed_actual_backend':'TBD','reported_token_basis':'Native SDK usage.total_tokens, sum once; billing components unverified','billing_usd':'TBD','candidate_vs_comparison_reported_token_change_percent':ratios,'order_seed':108,'model_sampling_seed':'TBD','native_cloud_search_gate':'TBD','canonical_promoted':False,'sealed_confirmation_used':False}
(OUT/'stage-progress.json').write_text(json.dumps(metadata,indent=2)+'\n')
labels={'none':'No skill','karpathy':'Karpathy','candidate':'Locate-first candidate','both':'Candidate + Karpathy (Both)'}
lines=['# Native agy Flask development — results','','Four native `agy` attempts completed with SDK SUCCESS and passed independent official grading. This reuses development issue `pallets__flask-5014` from SWE-bench Verified. One round, no confirmation and no promotion.','','| Skill | Solved | Reported tokens | Actor seconds |','|---|---:|---:|---:|']
for a,label in labels.items():
 r=byarm[a];lines.append(f'| {label} | {int(r["solved"])}/1 | {r["reported_total_tokens"]:,} | {r["elapsed_seconds"]:.1f} |')
lines+=['',f'Locate-first uses **{-ratios["none"]:.1f}% fewer** reported tokens than no skill and **{-ratios["karpathy"]:.1f}% fewer** than Karpathy, but **{ratios["both"]:.1f}% more** than Both. It does **not** beat every comparison here. Cross-task stability, actual billing and independently observed backend remain **TBD**.','','Each official report records one fail-to-pass and59 pass-to-pass successes, with no infrastructure failure. All four actors exited0 within their caps; no SDK errors, timeouts or auth rejection occurred. The original marker no-op control was independently rejected before inference.','','Requested native model: `gemini-3.8-flash-low`; actual backend routing is **TBD**, not inferred from the requested label. Native ELF1.2.16 was mounted readonly and SHA pinned. Reported counters use explicit terminal SDK `usage.total_tokens` once; cache/thinking components are not added again. Billing component completeness and invoice dollars are **TBD**.','','The frozen local/global four-start budget, runner/classifier/bridge/accounting/collector hashes, original prompt/source, native ELF and image were verified before calls. Order seed108 controls order, not model sampling. The pre-call auth classifier correction is preserved under `superseded-preparation/`. Classification tests distinguish terminal ERROR.error from benign source/tool text. An exclusive launch marker forbids automatic replay.','','Actors received uniform inline SKILL.md text and complete readonly resources. Private dataset, original test patch/gold and grader credentials were not mounted into actors. Stopped snapshots were converted to patches against trusted original source, ignoring actor Git metadata, and independently graded with `swebench5.0.2`. Three known unrelated source-suite cookie-domain failures remain disclosed; task grading passing does not prove full-suite cleanliness.','','Google OAuth was seeded once into a private persistent HOME outside Git. Updated authentication persists under `agy.lock`; host seed was never written. Original/refreshed exact credential scans and frozen artifact/report hashes pass in [audit.json](audit.json).','','[External-access audit](external-access-audit.json) retains native tool parameters and test/web/fetch candidate events. Local source/test mentions do not establish remote access. Native cloud-search gating and invisible network calls remain **TBD**; zero markers cannot establish clean held-out isolation. This is exposed public development, never confirmation.','','Artifacts: [results](results.json), [CSV](summary.csv), [stage progress](stage-progress.json), raw transcripts/patches/workspaces under `agy/`, and official reports/test outputs under `official/`. Canonical skill and sealed tasks are unchanged.']
text='\n'.join(lines)+'\n'
for a,b in [('and59','and 59'),('exited0','exited 0'),('ELF1.2.16','ELF 1.2.16'),('seed108','seed 108'),('`swebench5.0.2`','`swebench 5.0.2`')]:text=text.replace(a,b)
(OUT/'README.md').write_text(text);print(json.dumps(metadata))
