import pathlib,json,random,hashlib,sys
r=pathlib.Path('/data/wangjian/wj_code/dl_long/nvlab-sol-pi-skills/distill-skill-nvlabs-SoL-Pi');d=r/'tests/framework/refinement/development/local-qwen-independent-reads';sys.path.insert(0,str(d/'runtime'));import wrapper as W
native=r/'tests/framework/runtime/local-qwen/native-readiness/consumed-phase-2';base=json.loads((native/'plan.json').read_text())
tasks={'terminal':{'family':'terminal','task':'sanitize-git-repo','baseline':'/tmp/solpi-terminal-locate-first-baseline','prompt':'/tmp/solpi-refinement-terminal-bench-2/sanitize-git-repo/instruction.md','tests':'/tmp/solpi-refinement-terminal-bench-2/sanitize-git-repo/tests','image_id':'sha256:575d33f0522d38aa9978013294f4b03629fea2bd11ea82a32306197968b8e8ac','actor_workdir':'/app/dclm','expected_test_events':3},'go':{'family':'go','task':'go/food-chain','baseline':'/tmp/solpi-polyglot-go-smoke-v2/workspace','prompt':'/tmp/solpi-polyglot-go-smoke-v2/prompt.txt','image_id':'sha256:be1506c27383f1294c827041f4705d45a7342ca01273e7fbb47ff69df875b118','actor_workdir':'/work'},'swe':{'family':'swe','task':'pallets__flask-5014','baseline':'/tmp/solpi-refinement-flask-native-task-v2/workspace','prompt':'/tmp/solpi-refinement-flask-native-task-v2/prompt.txt','image_id':'sha256:10a67635ce037886b760a72f6eef8459beb6a0c6e070c0748a037839135acc45','actor_workdir':'/work','grader_image_id':'sha256:bf8242431f5c177d67996b3c888a0f51e4bb7bd0b67009bee6c70842baca1241','dataset':'/tmp/solpi-refinement-swe-data.json','python':'/tmp/solpi-refinement-harbor-venv/bin/python'}}
schedule=[];rng=random.Random(113)
for family in tasks:
 arms=list(W.ARMS);rng.shuffle(arms)
 for arm in arms:schedule.append({'id':family+'-'+arm,'family':family,'arm':arm,'round':1})
p={**{k:base[k] for k in ('shared_inference_locks','routing_certificate','hosthop_mode')},'status':'prepared_zero_starts_root_review_required','purpose':'Previously exposed fixed development only; no confirmation or goal-win claim','harnesses':['codex0.160.0'],'maximum_native_starts':12,'seconds_per_actor':180,'maximum_provider_POST_per_actor':16,'maximum_provider_POST_total':192,'retries':0,'order_seed':113,'schedule':schedule,'tasks':tasks,'candidate_sha256':W.sha(d/'frozen/candidate/SKILL.md'),'karpathy_sha256':W.sha(d/'frozen/karpathy/SKILL.md'),'arms':W.ARMS,'native_starts':0,'provider_POST':0,'stop_policy':'Quality failure never skips later fixed cells. Infrastructure, uncertain cleanup, auxiliary-accounting ambiguity or non-idle scheduler stops with durable partial evidence and no retry/replacement.','scope':'separate Qwen backend; never pool historical ChatGPT; hard goal remains five harnesses/three fresh families/three rounds','entrypoint':'run_screen.py --execute-development-screen --plan-sha256 EXACT; separately supplied root execution-authorization.json required','external_trees':{},'external_files':{},'source_hashes':{},'proxy_image_id':'sha256:be1506c27383f1294c827041f4705d45a7342ca01273e7fbb47ff69df875b118','resource_limits':{'actors':{'cpus':1,'memory_bytes':536870912,'pids':64,'tmpfs_bytes':67108864},'proxy':{'cpus':1,'memory_bytes':536870912,'pids':32},'graders':{'cpus':1,'memory_bytes':2147483648,'pids':128,'network':'none'}},'native_binary_sha256':'12eb3e81114588aca3b7998f4f19e8997b056aca08e57a7ca7c8a3ec8c652aad','timing':'180s per actor including create/inspect/start and 10s cleanup reserve; each provider stream40s/proxy45s; official grading separately bounded','publication':'Only metadata/source/hashes public; raw requests/responses/prompts/task work/official reports remain private /tmp outsideGit','runtime_origin':{'path':str(native),'copied_sources_sha256':{name:W.sha(native/name) for name in ['session.py','server.py','stream_proxy.py','run_native.py','wrapper.py']},'adaptation':'Independent copy: fixed twelve-cell screen,180s/16/192 caps, Responses-only strict terminal normalization, independent official grades, no quality-based schedule changes'},'source_snapshot_scope':'Frozen whole activated resources and Go grader; complete original task/Terminal tests/installed SWE package hash manifests validated at launch. Original task and SWE verifier contents remain private and external, no actor grader mounts.','accounting':'Strict unique terminal Responses usage+EOF, inclusive input+output, cache/reasoning subsets not added. Partial traffic lower bound, no savings claim if incomplete.'}
for t in tasks.values():
 p['external_trees'][t['baseline']]=W.files(t['baseline']);p['external_files'][t['prompt']]=W.sha(t['prompt'])
p['external_trees'][tasks['terminal']['tests']]=W.files(tasks['terminal']['tests'])
p['external_trees']['/tmp/solpi-refinement-harbor-venv/lib/python3.13/site-packages/swebench']=W.files('/tmp/solpi-refinement-harbor-venv/lib/python3.13/site-packages/swebench')
p['external_files'][tasks['swe']['dataset']]=W.sha(tasks['swe']['dataset'])
p['source_hashes']={str(x.relative_to(d)):W.sha(x) for x in sorted(d.rglob('*')) if x.is_file() and '__pycache__' not in x.parts and x.name not in ('plan.json','grading-plan.json','README.md','execution-authorization.json','grading-authorization.json')}
(d/'plan.json').write_text(json.dumps(p,indent=2)+'\n');print(W.sha(d/'plan.json'))

control={'purpose':'Independent official baseline/gold controls only, zero models','screen_plan_sha256':W.sha(d/'plan.json'),'maximum_official_controls':6,'maximum_oracle_setups':1,'combined_maximum_official_verifiers':7,'combined_maximum_oracle_setups':2,'control_uid':__import__('os').getuid(),'control_gid':__import__('os').getgid(),'prior_infrastructure_attempts':{'grading_plan_sha256':'b8b0c2354e3fed992dc7d660cd2302283cade9f5af7e948eddd40e3031ea4941','official_verifiers':1,'oracle_setups':1,'quality':'ungraded infrastructure permission failure; numeric baseline exit1 is not a functional negative','public_audit_sha256':W.sha(d/'consumed-grading-phase-1/grading-control-audit.json')},'native_starts':0,'provider_POST':0,'retries':0,'terminal_gold':'/tmp/solpi-refinement-terminal-bench-2/sanitize-git-repo/solution','go_gold':'/tmp/solpi-polyglot-go-smoke-v2/reference','gold_source_hashes':{},'source_hashes':p['source_hashes'],'deadlines':{'terminal_oracle_seconds':60,'terminal_go_grading_seconds':240,'swe_worker_seconds':300,'worker_TERM_seconds':3,'worker_KILL_seconds':3,'docker_cleanup_seconds':5,'docker_inspect_seconds':5},'privacy':'All gold contents, prepared workspaces and raw verifier logs remain0700private/tmp; gold is never actor-mounted; control report contains only metadata/hashes','protocol_note':'SWE empty patch runs official pristine tests with skip_patch=True and is always scored false; positive trusted gold uses ordinary patch application and exact same verifier image/test script. Report confirms full original reference F2P/P2P lists and actual expected test collection for any pass.'}
for key in ['terminal_gold','go_gold']:control['gold_source_hashes'][control[key]]=W.files(control[key])
(d/'grading-plan.json').write_text(json.dumps(control,indent=2)+'\n');print('grading',W.sha(d/'grading-plan.json'))
